### ISSUE TITLE
Failed to activate the fast-eslint package

### ISSUE THREAD

**Issue by jonmadison** [Adezandee/fast-eslint#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [fast-eslint](https://github.com/Adezandee/fast-eslint) package, v2.11.0

### Stack Trace

Failed to activate the fast-eslint package

```
At Cannot find module 'lodash.uniq'

Error: Cannot find module 'lodash.uniq'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jonmadi/.atom/packages/fast-eslint/lib/exec.js:7:28)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jonmadi/.atom/packages/fast-eslint/lib/index.js:9:15)
    at Module._compile (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
atomic-chrome, v0.3.0
chester-atom-syntax, v0.1.1
fast-eslint, v2.11.0
file-icons, v1.7.11
linter, v1.11.4
node-debugger, v1.7.0

# Dev
No dev packages
```

**Comment by Adezandee** [comment]
Hi @jonmadison, this is strange since this package is correctly listed here https://github.com/Adezandee/fast-eslint/blob/master/package.json#L54
Maybe atom/apm bug?

**Comment by jonmadison** [comment]
i'll try the update again later...I was reporting this directly from Atom's
error report dialog and admittedly didn't spend too much time investigating.

===
http://www.jonmadison.com/

**Comment by rsheldiii** [comment]
I'm having this as well, with all packages updated, on boot.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: [fast-eslint](https://github.com/Adezandee/fast-eslint) package 4.11.0


### Stack Trace

Failed to activate the fast-eslint package

```
At Cannot find module 'eslint-config-standard-react'
Referenced from: 

Error: Cannot find module 'eslint-config-standard-react'
Referenced from: 
    at ModuleResolver.resolve (/packages/fast-eslint/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/packages/fast-eslint/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/packages/fast-eslint/node_modules/eslint/lib/config/config-file.js:579:26)
    at configExtends.reduceRight (/packages/fast-eslint/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/packages/fast-eslint/node_modules/eslint/lib/config/config-file.js:431:26)
    at Object.loadObject (/packages/fast-eslint/node_modules/eslint/lib/config/config-file.js:566:35)
    at /packages/fast-eslint/node_modules/eslint/lib/config.js:85:46)
    at /packages/fast-eslint/node_modules/eslint/lib/cli-engine.js:466:23)
    at /packages/fast-eslint/lib/exec.js:64:14
    at exports.allowUnsafeNewFunction (/packages/fast-eslint/node_modules/loophole/lib/loophole.js:25:14)
    at initEngine (/packages/fast-eslint/lib/exec.js:63:3)
    at /packages/fast-eslint/lib/index.js:19:92
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334261)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:328743)
    at Object.activate (/packages/fast-eslint/lib/index.js:19:40)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3295584)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294996)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3292606)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294856)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294799)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382285)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381901)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331549)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381851)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381401)
    at t.loadState.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:710323)
```

### Commands

```
     -0:37.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:27.1.0 application:add-project-folder (div.github-Git-root)
     -0:24.7.0 command-palette:toggle (div.github-Git-root)
     -0:22.4.0 core:move-down (input.hidden-input)
     -0:22.3.0 core:confirm (input.hidden-input)
     -0:22.3.0 settings-view:view-installed-packages (div.github-Git-root)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.2.0 
ask-stack 2.2.0 
atomify 0.6.0 
autocomplete-modules 2.3.0 
busy-signal 2.0.1 
change-case 0.6.3 
editing-diff 0.2.1 
escape-utils 0.5.3 
fast-eslint 4.11.0 
file-icons 2.1.33 
firacode 0.3.0 
formatter 2.12.4 
formatter-clang-format 0.1.2 
goto-definition 1.3.4 
gruvbox-plus-syntax 1.3.1 
highlight-selected 0.16.0 
intentions 1.1.5 
invert-selection 1.0.0 
language-babel 2.85.0 
language-haml 0.32.1 
language-javascript-jsx 0.3.7 
language-openscad 0.4.3 
linter 2.3.0 
linter-coffeelint 2.0.18 
linter-eslint 8.5.5 
linter-jsonlint 1.4.0 
linter-rubocop 2.4.2 
linter-ui-default 1.7.1 
markdown-preview-plus 3.9.3 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.2.1 
minimap-selection 4.5.0 
open-git-modified-files 0.2.4 
pain-split 1.4.0 
pigments 0.40.2 
pretty-json 2.1.2 
pristine-ui 1.1.11 
project-manager 3.3.7 
react 0.18.0 
RebelChat 0.8.1 
ruby-block 0.3.6 
set-syntax 0.4.0 
sort-lines 0.19.0 
split-diff 1.6.0 
string-encoder 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
svg-preview 0.14.0 
sync-settings 0.8.6 
url-encode 0.5.0 
```

**Comment by Adezandee** [comment]
Hi @rsheldiii, this module doesn't come with the plugin. Did you install it globally ? `npm i -g eslint-config-standard-react`

**Comment by jeevasusej** [comment]
If install, locally for the project, how to configure for the particular project instead of globally.
